# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SimbirSoft' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimbirSoft
pod 'Alamofire'
pod 'SwiftLint'
pod 'SnapKit'
end
